### ISSUE TITLE
Projection on Stiefel manifold

### ISSUE THREAD

**Issue by panpat** [kul-forbes/ProximalOperators.jl#107]
Have you guys ever considered implementing the Euclidean projection on the Stiefel manifold? See for instance, Section IV in https://people.eng.unimelb.edu.au/jmanton/pdf/Manton_Opt_Alg.pdf

Orthogonality constraints are very useful in low rank approximation and many many other applications. It would be nice to see how your (our) algorithms compare, for instance, with manifold optimization methods which are typically used to solve such problems.

**Comment by lostella** [comment]
Yeah according to Prop 7 this should be very simple to implement
