### ISSUE TITLE
Is ProximableFunction no longer supported?

### ISSUE THREAD

**Issue by xinkai-zhou** [kul-forbes/ProximalOperators.jl#143]
The following no longer works.. 
`struct f <: ProximableFunction end`

Is `ProximableFunction` replaced by something else?

**Comment by lostella** [comment]
That abstract type was not very useful, so it was just removed. Now you can just implement your own type without subtyping anything, see eg https://github.com/JuliaFirstOrder/ProximalOperators.jl/blob/5b2845a2d34f61a4e002ee28801ae1de5da8639f/src/functions/indBallL1.jl#L14

The core API (prox!, prox, and so on) is defined in [ProximalCore](https://github.com/JuliaFirstOrder/ProximalCore.jl), and that is what you need to provide methods for, for your custom function types.

**Comment by xinkai-zhou** [comment]
I see.. Thank you for clarifying.
