### ISSUE TITLE
Completing Precompose

### ISSUE THREAD

**Issue by lostella** [kul-forbes/ProximalOperators.jl#15]
The `Precompose` calculus rule needs to be completed. Given `f` and a linear mapping `A`, we want to be able to compute the `prox!` of `x -> g(x) = f(Ax)`.

[As of now](https://github.com/kul-forbes/ProximalOperators.jl/blob/6a4c8535187d84f73be1df4aaf73c58182eb1392/src/calculus/precompose.jl) we are able to handle the case where `f` is precomposed with a diagonal mapping. In this case `A` is represented by `a`:

1. `a` is a `Real`: then the mapping is a multiple of the identity, in which case the rule can be applied regardless of the structure of `f`;
2. `a` is an `Array`: then `a` represents the mapping's diagonal, and the rule can be applied provided that `f` is separable (actually, if all elements of `a` are equal then this is the same of case 1., but we don't check that now); separability of `f` is detected by the presence of `prox!(f, x::Array, y::Array, gamma::Array)`, i.e., the possibility of specifying a different stepsize for each coordinate. See for example how the [hinge loss](https://github.com/kul-forbes/ProximalOperators.jl/blob/6a4c8535187d84f73be1df4aaf73c58182eb1392/src/functions/hingeLoss.jl) is defined in terms of the [sum-of-positive](https://github.com/kul-forbes/ProximalOperators.jl/blob/6a4c8535187d84f73be1df4aaf73c58182eb1392/src/functions/sumPositive.jl).

This structure presents a few drawbacks. I can think of:

- [x] Having a call with `gamma::Array` as fourth argument may create ambiguities: what if one wants to call the three-arguments `prox!`? Then `prox!(f, x::Array, gamma::Array)` clashes with `prox!(f, x::Array, y::Array, gamma::Real=1.0)`. **Remedy:** put the stepsize `gamma` as third argument, and the target (output) `y::Array` as fourth. This is backward incompatible but better now than never, and the more I think of it the more I'm convinced it's the right signature for `prox!`.
- [x] The linear mapping shouldn't need to be diagonal at all to apply this rule: it suffices that `AA'` (where `A'` is the adjoint mapping) is diagonal, conformably with the separability structure of `f` (constant diagonal always works, as stated for example in [Bauschke, Combettes, Prop. 23.32](http://link.springer.com/book/10.1007%2F978-1-4419-9467-7); any diagonal if `f` is separable, I don't have a reference for this but I'm sure it's easy to write down). For example, `A` may be a [rotation](https://en.wikipedia.org/wiki/Rotation_(mathematics)). How should this case be accessed? Calling `precompose(f, A)` where `A` is a `Matrix` may not do the job, because if `f` is function defined over some space of matrices, than such an `A` may very well represent the diagonal mapping `X -> A.*X` over that space.

The first issue is quite urgent I believe. For the second, there's room for discussion and experiments.

Whatever way is taken, completing the support for precomposition must go through:
- [x] Have all separable functions support the call to `prox!` with `gamma::Array`.

**Comment by mfalt** [comment]
What is the three argument prox? In-place computation in x? This doesn't seem like it could work efficiently with most functions?
Another alternative is to always let gamma be a keyword argument.

**Comment by lostella** [comment]
Yes, it is that: in-place computation in `x`. Right now it is defined at the very end of [ProximalOperators.jl](https://github.com/kul-forbes/ProximalOperators.jl/blob/6a4c8535187d84f73be1df4aaf73c58182eb1392/src/ProximalOperators.jl). Do you think it makes sense to have this? In the end, the user can always do `prox!(f, x, x)` if he wants to do that...

**Comment by mfalt** [comment]
Interesting, I just assumed that it wasn't always possible to do that kind of in-place prox, at least not efficiently for all functions. But it might not be as big of a problem as I thought.
However, I think it's common to assume that the arguments can't point to the same element. I have to think some more about this.

**Comment by lostella** [comment]
@mfalt aren't keyword arguments inefficient? I mean, don't they add a lot of overhead compared to non-keyword ones?

**Comment by mfalt** [comment]
I wasn't aware of this but I tested and it seems like there can be some significant overhead when a function is called with a keyword argument. There is no overhead for calling a function that is defined with kwargs if none are supplied though.

**Comment by lostella** [comment]
In fact it is not always possible to do the in-place evaluation of prox. I think in some functions I had to specifically be careful that x and y might reference the same arrays.

I agree that the 3-arguments prox! could easily go, and we can assume that in the 4-argument prox! x and y point to different arrays. Then in some cases it could work anyway, but that should not be the contract with the user.

I will create a PR for this, addressing the first tick box above. Then I'll see about the second.

**Comment by nantonel** [comment]
I wouldn't put `y` as fourth but as first instead!
looks more elegant to me, just compare the in-place with the non in-place calls:
`fx = prox!(y::Array, f, x::Array, gamma::Real=1.0)`
`y, fx = prox(f, x::Array, gamma::Real=1.0)`

**Comment by lostella** [comment]
Or that, yes, even better.
