### ISSUE TITLE
Inner constructors

### ISSUE THREAD

**Issue by mfalt** [kul-forbes/ProximalOperators.jl#19]
To suppress all warnings on julia 0.6 we need to fix the inner constructors. The commit 9edfe1a follows the recommended way from
```julia
type Foo{T}
    x::T
   Foo(x)= new(x)
end
````
to
```julia
type Foo{T}
    x::T
   Foo{T}(x) where {T} = new(x)
end
````
which is not compatible with julia 0.5.
There seems to be a way to do it compatible with 0.5:
```julia
type Foo{T}
    x::T
    (::Type{Foo{T}}){T}(x::T) = new{T}(x)
end
```
maybe we should use this instead?
I am not able to understand why the backwards compatible way is not the recommended way.

**Comment by lostella** [comment]
To better understand this new syntax: type constraints go in the curly braces after ``where'', right? Do you have ideas on how long it will take for 0.6 to be released? The backward compatible syntax is ok, but sacrifices readability a bit... but will be temporary I guess and we will drop the support of 0.5 soon enough I guess

**Comment by mfalt** [comment]
Yes, see for example the commit I made.
I also think dropping 0.5 is fine as soon as 0.6 is released. The old version of ProximalOperators will still be available. They still have a decent amount of issues so it might be a while, but I wouldn't be surprised if we get a RC in a few weeks.
