### ISSUE TITLE
Type instability

### ISSUE THREAD

**Issue by mfalt** [kul-forbes/ProximalOperators.jl#23]
There is some bad type instability in some of the functions, for example IndAffine
```julia
immutable IndAffine{T <: RealOrComplex} <: IndicatorConvex
  A::AbstractArray{T,2}
  b::AbstractArray{T,1}
  R::AbstractArray{T,2}
  ....
```
since there is no information on the type arrays, any use of these will result in type instability.
With julia 0.6 we are able to do diagonal dispatch
```julia
immutable IndAffine{R <: RealOrComplex, M<:AbstractArray{R,1}, V<:AbstractArray{R,1}} <: IndicatorConvex
  A::M
  b::V
  R::M
  ....
```
Here assuming that `A` and `R` will be of the same array type. If we want `b` to be of the same type we could enforce this in the constructor without any penalty.
I can create a PR for this unless anyone have any issues with it.

**Comment by lostella** [comment]
Yes, using "type constraints" like in your second example was for sure something to be done for 0.6. This can also be useful in other contexts: in defining `prox!` for example, we can force the input-output vectors (and the stepsize `gamma`) to have the same type of elements, like in

```julia
function prox!{R<:Real}(y::AbstractArray{R}, f, x::AbstractArray{R}, gamma::R)
  ...
end
```

Of course, by doing so we force the user to be extremely diligent with types :-)
But again, we should do this when dropping compatibility with 0.5 I guess, so you can either create a PR and then we merge after merging your 0.6 branch, or you can directly work on the 0.6 branch.

**Comment by lostella** [comment]
Closing this since the particular issue described here was solved, and most of the other types seem to have followed the same design. Feel free to open new issues in case other type instabilities are there.
