### ISSUE TITLE
Using predicates instead of types

### ISSUE THREAD

**Issue by lostella** [kul-forbes/ProximalOperators.jl#25]
Types in Julia are great. But types in Julia should not be overused. As pointed out by @mfalt, it is rather complicated to encode properties of `ProximableFunction` objects using Julia types: the simple fact that `f` is `ProximableConvex`, for example, is lost when constructing `Postcompose(f)`. What makes more sense, probably, are predicates of the form `is_convex(f)`, `is_cone(f)` and so on, that inspect object `f`. See #14 for a related discussion.

**Comment by mfalt** [comment]
I completely agree, I think types should be used for what they are good for; dispatching functions and inferring types for efficient code.
I don't see that there would be any loss in efficiency by removing these abstract types,.
