### ISSUE TITLE
Project on operator graph and IndAffine row rank

### ISSUE THREAD

**Issue by mi-volodin** [kul-forbes/ProximalOperators.jl#38]
Hello, @lostella !
I was looking for the reliable library for proximal operators evalutation on github and I liked this one because of the general architecture and implementation (👍🏻).

However, what I am missing was the projection to an operator graph case {(x,y) | Ax=y}. Since it also could be done via Affine projection - I decided to look through the code and discovered one interesting feature.
The implementation requires full rank matrices (so the QR method for Pseudo-inverse might be applied) which... might be my case.

So, I have the following questions:

1. was there any reason to do so (I mean deliberately prohibit) or it's just "not implemented yet" for the case m<n. In the least case I would try to participate and add this functionality (not sure it would be possible, but I'll try). Even SVD method might be suitable (since pinv could be stored inside the struct/immutable).

2. what do you think about adding the graph project case. It could be done through affine projection, but as far as I know it has it's own heuristics for efficient calculations.

**Comment by mfalt** [comment]
I think these are very good points. I can only answer in regard to my own applications.

1. In the applications I'm working it's usually assumed that the matrix has full row rank. The other cases consist either of that no solution exist, in which case the projection is not defined, or that there are duplicate constraints, which could be removed in some pre processing step.

2. I have been working on an implementation of this, mainly an indirect method using some conjugate gradient. If you have any ideas on which algorithm to use I would be very happy to hear your input. My code is mostly in the [FirstOrderSolvers](https://github.com/mfalt/FirstOrderSolvers.jl) package, but I'm not sure if it contains a working version yet, or if it is correct. This, or another version, could probably be added/moved to this package.

**Comment by mi-volodin** [comment]
Well, I'm interested in implementation of operator block-splitting algorithm, described [here](http://web.stanford.edu/~boyd/papers/block_splitting.html). I have already implemented it in MATLAB but ... there's a million "but"s about matlab. So now I'm doing the same thing in Julia.

1. In block splitting it is generally hard to think about row rank - the heuristic of how to pick up blocks has more importance. So, the case when `m<n` is normal. However, I asked here about it, because current implementation is way better for full row rank and SVD variant (see [wikipedia](https://en.wikipedia.org/wiki/Moore–Penrose_pseudoinverse), Construction) has several drawbacks.
But if it is not prohibited - I'd like to add this case implementation (if I could, pinv() of Julia does not accept sparse matrices, so I'll try to find a workaround).

The problem I have - I'm not really experienced in Julia developing, so I might need the code-review help from someone.

2. Hm. To be honest - I just have an experience of using Boyd and Parikh matlab package of proximal operators. Here's the translation to julia [github project](https://github.com/johnmyleswhite/Proximal.jl/blob/master/src/project_graph.jl), I did not tested it, but it looks quite the same as Matlab variant published by authors - at least the idea is clear.
I'm going to implement it by myself, because I need it, but I will happy to contribute and add it to this package. As I mentioned - I like the design, so my implementation will follow it anyway.

So what, greenlight? 😄
I have adressed @lostella, because I saw a lot of work pending to be merge in the master. There are lot's of changes (and also in `IndAffine`), so I do not sure whether it will be worth trying - resolving conflicts would be difficult.

**Comment by lostella** [comment]
Hey Dmitry, thank you for the appreciation!

As Mattias already mentioned, in the IndAffine case it really makes sense to restrict to the full row rank case (and thus, fat matrices, m <= n) because that's when the set of solutions to Ax=b is certainly non-empty.

If I understand, projecting (x, y) onto the graph of A could in fact be formulated using IndAffine with [A, -I] (which is full row rank) and 0 as right hand side. This has the disadvantage though of loosing the structure of (x, y), that is, you will have to merge x and y into a single vector. Also, as you mentioned, computations may be tailored for this case.

I'm all in if you want to contribute with a specific type of ProximableFunction for this case, please do :-) just open a PR when you have an idea on how it could be like and we'll figure out what's missing or to be fixed. Maybe, as I was mentioning above, you want to implement a function that takes pairs of Array objects (x, y) as input, rather than a single Array?

As per the pending PR: I didn't have time to do anything about it in the last week, but I'll be back on it very soon to merge it, I just need to think through some last details I wanted to check.

**Comment by mi-volodin** [comment]
Well, from my point of view - it's a very rare case when you try to solve an optimization problem with nonexistent solution )) It is usually done analytically, so the case m>n is normal. In fact - row rank is nothing, you should check Kroneker-Kapelli conditions - the (not row) rank of the coefficient matrix `A` and correspoinding rank of `b`. In math-modeling if you do not perform presolve - it is a common case to have linear dependent rows of `A`.

But anyway, IndAffine is not good for operator graph projection also because the better heuristics could be used to solve the problem of graph projection. See Appendix A of the [paper](https://web.stanford.edu/~boyd/papers/pdf/block_splitting.pdf).

Ok, I'll do the PR, most probably - next week. I already did the case for sparse matrices. Dense matrices should be solved other way, so I'll add it and the create PR.

Thanks!

**Comment by mi-volodin** [comment]
Since I have a PR, I think this Issue could be closed. All necessary information is inside the PR track.
