### ISSUE TITLE
Compatibility with 0.7/1.0

### ISSUE THREAD

**Issue by lostella** [kul-forbes/ProximalOperators.jl#47]
Currently tests fail on nightly. Since feature freeze for Julia 1.0 is about to hit, it will be soon time to start making the package forward-compatible. We can use this space to list criticalities and discussions on that regards.

**Update - 25/03/2018**

I'm currently going through this. General things found so far:
- [x] the `Base.LinAlg` module is now `LinearAlgebra`
- [x] `Base.A_mul_B!` has become `LinearAlgebra.mul!`
- [x] `Base.Ac_mul_B!(y, A, x)` is now `LinearAlgebra.mul!(y, adjoint(A), x)`
- [x] sparse factorizations moved to the `SuiteSparse` module (from `Base.SparseArrays`)
- [x] random number generation functions moved to the `Random` module (from `Base`)
- [x] `@printf` moved to the `Printf` module (from `Base`)
- [x] warnings are generated when `.+` (and similarly for other operators) is not appropriately spaced away from the operands (example: `2.+x` confuses the parser on the nature of first summand `2` or `2.0` I guess)
- [x] when broadcast was not explicitly used, e.g. `x::AbstractArray + y::Number`, now we get a warning
- [x] `zeros(a::AbstractArray)` is deprecated in favor of `zero`, `fill`, `fill!`
- [x] the old form `function f{T}(x::T) ... end` now generates warnings, I'm getting rid of these everywhere, in favor of the `where` notation
- [x] docstrings should be 1 newline away from what they refer to (i.e., no blank line in between, warning otherwise)
- [x] `findmax` does not work on generator expressions anymore

Package specific issues:
- [x] `dspev!` and `dspevV!` are broken

**Comment by lostella** [comment]
Transition branch: https://github.com/kul-forbes/ProximalOperators.jl/tree/julia-0.7

**Comment by nantonel** [comment]
This list is very useful! Thanks for sharing!
