### ISSUE TITLE
Bundle method for non-differentiable optimisation

### ISSUE THREAD

**Issue by elchiconuevo** [kul-forbes/ProximalOperators.jl#53]
Bundle method has been widely adopted to compute the subgradients within a lagrangean relaxation framework due to faster convergence compared to the traditional cutting plane algorithms. I'm looking for an implementation of the bundle method in Julia in order to employ them within my lagrangean heuristic. Are there any existing implementations of the bundle method in Julia? If not, would it be possible to request for one?

**Comment by lostella** [comment]
This package only implements first order primitives for various objective functions: you may use them to implement the algorithms you’re looking for (although I’m not familiar with them), but this package is not the right place to include them.

You may take a look to the algorithms implemented in ProximalAlgorithms.jl to see if bundle methods may fit there.

Closing!
