### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by lostella** [kul-forbes/ProximalOperators.jl#6]
I made a PR to JuliaLang/METADATA.jl in order to register the package, and the issue of the package name was raised. You can see the PR [here](https://github.com/JuliaLang/METADATA.jl/pull/6850).

Personally I don't dislike Prox.jl, but I understand that it probably speaks for itself only to someone who writes "\prox" or "\mbox{prox}" a lot in their papers. I guess the following are viable options:
1. Proximal.jl
2. ProximalOperators.jl

I like option 2. better: it is on the same line as LinearOperators.jl. Also, in option 1., "proximal" what? I understand that as far as packages names are concerned, brevity is discouraged in favor of clarity. What do you think?

**Comment by nantonel** [comment]
I think ProximalOperators.jl is the best option!

**Comment by mfalt** [comment]
Agree, ProximalOperators.jl sounds good.

**Comment by domagojherceg** [comment]
Hi guys, 
my vote goes to ProximalOperators.jl on the basis of clarity. Maybe even ProxOperators.jl could be considered? But then again, this is also kind of obscure.
