### ISSUE TITLE
Fix docs deployment

### ISSUE THREAD

**Issue by lostella** [kul-forbes/ProximalOperators.jl#67]
Documentation stopped being pushed a couple of releases ago. I suspect [this](https://github.com/kul-forbes/ProximalOperators.jl/blob/master/docs/make.jl#L19) could be the culprit.

Apart from this, the docs/travis configuration should probably be updated.

**Comment by nantonel** [comment]
I think we had a PR in StructOpt concerning this issue https://github.com/kul-forbes/StructuredOptimization.jl/pull/16
