### ISSUE TITLE
precompilation failing in Julia 1.1

### ISSUE THREAD

**Issue by nantonel** [kul-forbes/ProximalOperators.jl#70]
Seems like there ProximalOperators is not passing test in Julia 1.1 with quite weird errors:
```julia
ERROR: LoadError: LoadError: StackOverflowError:
```

I did some investigation by setting pre-compilation off by typing 
```julia
__precompile__(false)
```
in the main module.

What I got is a strange error in `IndFree`, specifically in the call:
```julia
prox!(y::AbstractArray{T}, f::IndFree, x::AbstractArray{T}, gamma::AbstractArray{T}) where {R, T <: RealOrComplex{R}} = prox!(y, f, x)
```
and in `LeastSquaresDirect` in the function:
```
function solve_step!(y::AbstractVector{D}, f::LeastSquaresDirect{R, RC, M, V, F}, x::AbstractVector{D}, gamma::R) where {R, RC, M, V, F <: SuiteSparse.CHOLMOD.Factor{RC}, D <: RealOrComplex{R}}
```
I didn't investigate further but leave these notes which are hopefully useful to solve this issue. 
Errors seem related to typing/subtyping stuff.

**Comment by lostella** [comment]
I'm not sure how #71 solved the problem, but the typing in LeastSquaresDirect needed to be simplified and that apparently solved it. However, I just saw [this](https://github.com/JuliaLang/julia/issues/30741) which might have been related
