### ISSUE TITLE
Strange errors in test Julia 1.1

### ISSUE THREAD

**Issue by nantonel** [kul-forbes/ProximalOperators.jl#73]
There are some strange errors in the tests. See [Travis line 192](https://travis-ci.org/kul-forbes/ProximalOperators.jl/jobs/490643138). These do not appear in [Julia nightly](https://travis-ci.org/kul-forbes/ProximalOperators.jl/jobs/490643141) so it's possible it's some Julia issue.

**Comment by lostella** [comment]
I’ve seen other weird things with Julia 1.1 on macOS, see #84. Since Julia 1.1 is unsupported, I would just unsupport it myself :-)
