### ISSUE TITLE
Non convex soft thresholding operator

### ISSUE THREAD

**Issue by patwa67** [kul-forbes/ProximalOperators.jl#75]
In the demo examples of the Lasso there is the ordinary soft thresholding operator defined as S = sign max{0,|x|-alpha}, which in the ADMM version translates to ```prox!(z, g, x + u, gam)```. In eq. (13) of Chatrand and Wohlberg (https://www.researchgate.net/publication/255907067_A_Nonconvex_Admm_Algorithm_for_Group_Sparsity_With_Sparse_Groups) they suggest a more flexible soft thresholding function of the form S = sign max{0,|x|-alpha^(2-p)|x|^(p-1)} ,where p is set to 1(the ordinary Lasso) , 0.5, 0 or - 0.5. My question is if there is some way to implent this soft thresholding using the tools available, or is some new norm function needed?

**Comment by lostella** [comment]
Hi Patrik, this library of proximal mappings is somewhat function-centric,
that is, each implementation of prox and prox! has some cost function that
originates it. So yes, the way of including such shrinkage mappings would
be to add a function type.

I’m not familiar with that paper: does it provide some sort of norm-like
function for each of the two cases p=0.5 and p=-0.5?

**Comment by patwa67** [comment]
I think the idea is to split up the L1 norm into scalar function mappings, eq. (15). I guess this is related to your separable sum function. They say that this function g(w) grows like (|w|^(p))/p + C for some C.
