### ISSUE TITLE
nonconvex prox calculus rule

### ISSUE THREAD

**Issue by panpat** [kul-forbes/ProximalOperators.jl#81]
Is there support for computing the prox of the pointwise **minimum** of proximable functions?
Suppose 
f=min{f_1,...,f_N}
Then 
prox_{γf}(x)=prox_{γf_i*}(x) 
where 
i*\in\argmin{f_1^γ(x),...,f_N^γ(x)}
and f_i^γ is the Moreau envelope of f_i.

This is very useful. For instance it can be used to compute the projection onto union of sets. One particular example I'm interested in is C={x| |a'*x|=b}={x| a'*x=b}\cup{x| a'*x=-b}.

Are you planning to include this anytime soon?

**Comment by lostella** [comment]
Interesting! No, this is not there yet, but seems pretty innocent. I’ll give it a shot and let you know.
